package graph

// This file will be automatically generated by `gqlgen`, it MUST NOT be edited by hand.

import "context"

type Resolver struct{}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() QueryResolver {
	return &queryResolver{r}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver {
	return &mutationResolver{r}
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() UserResolver {
	return &userResolver{r}
}

type queryResolver struct{ *Resolver }

func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	// TODO: Implement database query for single user
	return &User{
		ID:    id,
		Name:  "Sample User",
		Email: "user@example.com",
	}, nil
}

func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	// TODO: Implement database query for all users
	return []*User{}, nil
}

type mutationResolver struct{ *Resolver }

func (r *mutationResolver) CreateUser(ctx context.Context, input CreateUserInput) (*User, error) {
	// TODO: Implement database insertion
	return &User{
		ID:    "1",
		Name:  input.Name,
		Email: input.Email,
	}, nil
}

type userResolver struct{ *Resolver }
