// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
